// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button.vue')['default']
    Carousel: typeof import('./src/components/Carousel.vue')['default']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
